heat_template_version: 2015-04-30
description: Template to Avi Heat resources
resources:
  hm:
    type: Avi::HealthMonitor
    properties:
      name: "mytesthm"
      receive_timeout: 2
      failed_checks: 2 
      successful_checks: 2 
      send_interval: 2
      type: HEALTH_MONITOR_TCP
